mp:
  jwt:
    verify:
      publickey:
        location: publicKey.pem
      issuer: tickets-backend

smallrye:
  jwt:
    sign:
      key:
        location: privateKey.pem

quarkus:
  smallrye-jwt:
    enabled: true
    token:
      header: Authorization
      cookie: Bearer
  application:
    name: API Tickets
  datasource:
    db-kind: postgresql
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    reactive:
      url: postgresql://localhost:5432/tickets
  hibernate-orm:
    database:
      generation: drop-and-create
